### ISSUE TITLE
BUG: Subscribe button pass empty datas to the stripe API 

### ISSUE THREAD

**Issue by Jackie098** [Jackie098/ignite-ignews#1]
When the user does login through the button "Subscribe now", the same:

1) Don't take redirection to Checkout Payment after finishing the login
2) When creating a new user in the stripe API during the payment process, the data are passed empty

**Comment by Jackie098** [comment]
Updating:

link: https://next-auth.js.org/errors#jwt_session_error 

```
{
  message: 'decryption operation failed',
  stack: 'JWEDecryptionFailed: decryption operation failed\n' +
    '    at gcmDecrypt (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/jose/dist/node/cjs/runtime/decrypt.js:67:15)\n' +
    '    at decrypt (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/jose/dist/node/cjs/runtime/decrypt.js:92:20)\n' +
    '    at flattenedDecrypt (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/jose/dist/node/cjs/jwe/flattened/decrypt.js:119:52)\n' +
    '    at async compactDecrypt (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/jose/dist/node/cjs/jwe/compact/decrypt.js:18:23)\n' +
    '    at async jwtDecrypt (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/jose/dist/node/cjs/jwt/decrypt.js:8:23)\n' +
    '    at async Object.decode (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/next-auth/jwt/index.js:64:7)\n' +
    '    at async Object.session (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/next-auth/core/routes/session.js:41:28)\n' +
    '    at async AuthHandler (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/next-auth/core/index.js:158:27)\n' +
    '    at async NextAuthHandler (/home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/next-auth/next/index.js:24:19)\n' +
    '    at async /home/carlos/Documents/codes/personal/knowledge/ignite-frontend/classes/ignews/node_modules/next-auth/next/index.js:60:32',
  name: 'JWEDecryptionFailed'
}
```
